### ISSUE TITLE
Server crash when applying raw ore loot modifier

### ISSUE THREAD

**Issue by FeikoJoosten** [ItsBlackGear/CavesAndCliffsBackport#1]
I used the item `chthonic extractor` from [tetra](https://www.curseforge.com/minecraft/mc-mods/tetra). And whenever I used it, I'd crash the server.

[crash-2021-11-06_19.58.11-server.txt](https://github.com/ItsBlackGear/CavesAndCliffsBackport/files/7491506/crash-2021-11-06_19.58.11-server.txt)

**Comment by ItsBlackGear** [comment]
hopefully this should have been fixed

**Comment by ItsBlackGear** [comment]
fixed in 7.1.1
