### ISSUE TITLE
Accept any copper ingot to craft a copper block?

### ISSUE THREAD

**Issue by ephys** [ItsBlackGear/CavesAndCliffsBackport#10]
It's currently not possible to craft a copper block from other mods copper

![image](https://user-images.githubusercontent.com/1280915/142250579-7e5228ae-3fb8-452d-8a35-53a05e855c87.png)

The other way around does not work either 

![image](https://user-images.githubusercontent.com/1280915/142250691-5c717040-df0f-4ce4-b9d5-af11a82e38b5.png)

**Comment by ItsBlackGear** [comment]
this will be added c: thanks for the request

**Comment by ItsBlackGear** [comment]
fixed and pending to update
