### ISSUE TITLE
Crash when a shulker bullet causes another shulker to spawn

### ISSUE THREAD

**Issue by ephys** [ItsBlackGear/CavesAndCliffsBackport#12]
Here is the crash report :) https://gist.github.com/ephys/78161f5c852205b1498088e0a6b8280c

**Comment by ItsBlackGear** [comment]
you're still using 7.0, the issue was fixed in 7.1.4 👀 update and the issue will be gone c:

**Comment by ephys** [comment]
Ooh sorry and thank you for the fix :)
