### ISSUE TITLE
[BUG] Deepslate ores are not registered as propper ore feature.

### ISSUE THREAD

**Issue by KKotik** [ItsBlackGear/CavesAndCliffsBackport#17]
Deepslate ores are not registered as propper ore feature, so I can't disable them with side sources like KubeJS. Also I think it will be good to have config option to disable them with that bug fix.

**Comment by Pockett-Dev** [comment]
Hoping there's an update for this soon, desperately needing this :(

**Comment by ItsBlackGear** [comment]
fixed and pending to update c:
