### ISSUE TITLE
[BUG] Potentional issue with BetterMineshafts compat. Need testing!

### ISSUE THREAD

**Issue by KKotik** [ItsBlackGear/CavesAndCliffsBackport#18]
When both mods installed, regular minecraft:mineshaft structure start to appear. Need testing, not sure about this one, but I think it might be related.

**Comment by BloodyNecroZ** [comment]
I've submitted my testing to the mod author.
https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues/79
