### ISSUE TITLE
[BUG, potentially not important] Clock put on item frame doesn't update at first

### ISSUE THREAD

**Issue by Toma400** [ItsBlackGear/CavesAndCliffsBackport#20]
As in description, I found out that coming out of my Nether portal, the clock was showing day, when in reality there was night.
I needed to take it from the item frame for it to reset.
The issue does not remain, as everything is working (clock is going further), it just "freezed" at its default state I assume. Probably nothing really worthy the attention, but just reporting that, just in case.

**Comment by ItsBlackGear** [comment]
i wasn't able to replicate this issue after a few attempts, so i'll assume that the issue may not be cause of the mod 👀 if i get notified of it again then i'll reopen the issue
