### ISSUE TITLE
[BUG]Cave chunks breaking when generating around Beach biomes.

### ISSUE THREAD

**Issue by AutumnalFox** [ItsBlackGear/CavesAndCliffsBackport#22]
Cave chunks get hard cutoff around Beach biomes leaving some caves with unnatural shapes, pictures; 
![2021-12-04_22 04 54](https://user-images.githubusercontent.com/77494785/144729880-493bf488-5505-4cde-bec9-a92e562e490e.png)
![2021-12-04_22 04 39](https://user-images.githubusercontent.com/77494785/144729884-f356513b-5bda-4cc0-bfa2-7cfe2d749c36.png)
![2021-12-04_22 04 57](https://user-images.githubusercontent.com/77494785/144729912-5bf3db68-a86f-4de5-8d3d-dc1d91667a86.png)
 
I've noticed this only happens around the edge of the ocean, so the beach. To reproduce just fly around on spectator mode around at cave level in a beach biome next to an ocean.

I've tested with only CaveApi and CCB on their most recent versions (12-4-2021).

**Comment by ItsBlackGear** [comment]
this is a vanilla behavior for carvers, they stop generating in oceans to prevent clashes with ocean carvers and filling caves with water (trust me, it's not as pretty as it sounds..)
