### ISSUE TITLE
Causes the optifine Fov effects when set to zero to be set to max again. So turns on Fov effects when it's set to 0.

### ISSUE THREAD

**Issue by JetpackRescue** [ItsBlackGear/CavesAndCliffsBackport#23]
In video settings, quality or detail settings there's an fov effects slider, this mod makes it not work.

**Comment by WolfTM** [comment]
Please give us more details, 
What version of the mod are you using?
What version of Optifine are you using?
What game version are you on?
Forge or Fabric?
Any examples?

You can also join our discord for faster support: https://discord.gg/hs4AdABdyn

- WolfTM
BGMods Staff

**Comment by ItsBlackGear** [comment]
confirmed issue and fixed it, pending for update
