### ISSUE TITLE
[INCOMPATIBILITY BUG] Valhelsia Structures Bone Piles Float

### ISSUE THREAD

**Issue by Reshirou** [ItsBlackGear/CavesAndCliffsBackport#24]
This is someone else's image here but it gets the point across, we have the same bug.

Caused by Caves n Cliffs Backport, not Cave Biomes API. With my full modlist excluding CnCB the bone piles dont float anymore

![image](https://user-images.githubusercontent.com/19141286/144982247-b449a72d-f58d-402d-ab15-dc0211f097af.png)

**Comment by ItsBlackGear** [comment]
confirmed! took a while to figure out why was this happening but finally got it fixed, pending for update!
