### ISSUE TITLE
Work with other mods?

### ISSUE THREAD

**Issue by SpedicyWasTaken** [ItsBlackGear/CavesAndCliffsBackport#26]
The cave biomes aren't generating. I'm using terraforged and quark, are they able to generate with those or is something broken?

**Comment by StrangerSon71** [comment]
Terraforged breaks cave biomes.

**Comment by SpedicyWasTaken** [comment]
That's what I feared. Thank you!

**Comment by WolfTM** [comment]
> The cave biomes aren't generating. I'm using terraforged and quark, are they able to generate with those or is something broken?

Cave Biomes cannot generate in TerraForged.
For more information join our discord: https://discord.gg/hs4AdABdyn

- WolfTM
BGMods Staff
