### ISSUE TITLE
Compat with simply terrain?

### ISSUE THREAD

**Issue by Elitelmao** [ItsBlackGear/CavesAndCliffsBackport#29]
I didn't really test with SIT but ill like to know everything that's not compat with SIT generation

**Comment by Elitelmao** [comment]
mod in question https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain

**Comment by ItsBlackGear** [comment]
it is compatible with SIT, haven't received any information about incompatibilities related to SIT
