### ISSUE TITLE
Ore Generation Uncontrollable

### ISSUE THREAD

**Issue by RobertHDPotatoes** [ItsBlackGear/CavesAndCliffsBackport#3]
It seems that the recent 7.0 update introduced some changes to ore generation, in particular Diamond Ore generation. This has made it so mods like OreTweaker or Large Ore Deposits are no longer able to completely remove Diamond Ore Generation from the overworld, or change how Diamond ore spawns. My suggested solution to this problem is to add a config option to enable/disable the changes made by Caves and Cliffs, or to simply somehow make the ore generation in Caves and Cliffs compatible with the previously mentioned mods.

**Comment by ItsBlackGear** [comment]
Noted! ^^ this shall be fixed soon

**Comment by ItsBlackGear** [comment]
fixed in 7.1.2
