### ISSUE TITLE
Backport still use the texture with an extra gray pixel

### ISSUE THREAD

**Issue by Jukabofy** [ItsBlackGear/CavesAndCliffsBackport#30]
![image](https://user-images.githubusercontent.com/87483832/147360712-6b3efd42-70c2-4ead-8a8b-d2ebc24dbe37.png)

I see the backport still use the texture with an extra gray pixel
Just it, a visual problem

**Comment by ItsBlackGear** [comment]
problem confirmed and fixed c: pending for update
