### ISSUE TITLE
Question - Do ores follow the vanilla spawn rates? 

### ISSUE THREAD

**Issue by Kadinumoto** [ItsBlackGear/CavesAndCliffsBackport#44]
I'm working on a modpack and I want to tweak some of the ore generation but I was wondering if there is any documentation about how copper and the deepslate ores spawn and if they use the vanilla rates. Thank you for your time!

**Comment by ItsBlackGear** [comment]
howdy o/

copper follows the vanilla rates c:

**Comment by Kadinumoto** [comment]
Thank you for answering!
