### ISSUE TITLE
Candles placement not working correctly

### ISSUE THREAD

**Issue by Toma400** [ItsBlackGear/CavesAndCliffsBackport#5]
When I tried to place candle, some surfaces don't let me place more than one candle at the time - they are totally valid places though. I happened to place more candles once, but it was only one time, and this time I've seen small hitbox of candle (while I usually don't when this problem happen). I tried to both clicking on candle and on surface I was placing.

I use Forge 36.2.0 for 1.16.5
Other mods installed, if needed:
> Additional Lights
> Atum
> Better Badlands
> BetterEnd
> Betterlands
> Chipped
> Curios
> Customizable Elytra
> Guard Villagers
> Immersion
> JEI
> Mosaic Blocks
> OptiFine
> Polymorph
> Quark
> Shroomed
> Small Ships
> Spires of Baedoor
> The Desolat
> Wastelands of Baedoor
> Waystones
> Xenoclus 2

**Comment by ItsBlackGear** [comment]
what kind of surfaces? :0

**Comment by ItsBlackGear** [comment]
let me know if the issue persists in the latest update (7.1.3)

**Comment by Toma400** [comment]
Okay, I found the detail that can help you: if you shift and click on block, then it only places one and don't let you do more. I found out that because I used GUI-related block and trapdoor, both of them I had to shift to avoid using it instead of building.
It persists in 7.1.3 unfortunately.
There's workaround that you can place temporary block nearby and use it to place candles in position you want. I used it to place these candles (the block below them opens GUI when right-clicked):
![2021-11-09_20 01 30](https://user-images.githubusercontent.com/65849429/140987932-dfee668a-1054-416d-93f6-e2940d00edda.png)

**Comment by ItsBlackGear** [comment]
oh, that happens to be vanilla behavior actually
![imagen](https://user-images.githubusercontent.com/68313143/140997400-87b093a2-af69-4630-a67a-ee4f4bf11553.png)
there's an easier workaround to place more candles in it, once you place the candle by shift-clicking you'll have to click the candle that you've placed, it will add more candles into the block without the need of a temporary one
![imagen](https://user-images.githubusercontent.com/68313143/140997594-8504014e-11dc-4e14-9c4f-325cfe05d34e.png)
so it's working as intended c: also cool table :0 from what mod is it?

**Comment by Toma400** [comment]
Okay, I see it now, sorry for the trouble ^^' although I am pretty sure that this wasn't working that way in my previous version (the hitboxes just wasn't showing at all), so the fix worked well, I just didn't realise it for some reason.

And thanks! This table is from my indev mod, Spires of Baedoor, adding vanilla-friendly magic. I teamed up with great texture artist indeed :D

**Comment by ItsBlackGear** [comment]
:0 oooo i would love to see it once it's out! :D vanilla-friendly magic is something that i would love ingame

**Comment by Toma400** [comment]
Same, I missed so much mods like Electroblob's Wizardry for newer versions of Minecraft, hence the decision to do something like that myself.
If you want, I'll let you know once the mod goes fully public ^^ (for now it's only available on Discord server of mine, but it's extremely early version)

**Comment by ItsBlackGear** [comment]
:D
