### ISSUE TITLE
ShulkerBulletEntity / ShulkerEntity Crash

### ISSUE THREAD

**Issue by SHXRKIEgg** [ItsBlackGear/CavesAndCliffsBackport#6]
So I have updated my Better MC Modpacks with the new Caves and Cliffs Update and Updated my Medieval MC Modpacks but I specifically didn't update my Medieval MC Modpack with new Caves and Cliffs Update. and so in all the Better MC Packs there seems to be a crash in the End with ShulkerEntity. Now this could possibly not be your mod at all but the crash doesn't say much of what mod is causing it but it seems most likely to be the new Caves and Cliffs Update and it also mentions Caves aand Cliffs Mixins at the start. Let me know what you think.

Crash https://pastebin.com/s2VL48Pw

**Comment by ItsBlackGear** [comment]
oh i see the cause, you're currently using the 7.1.1 version which mentioned to fix the issue but apparently didnt, i've released two new hotfixes today, one of them fixing that issue because i used to do mixins for that one but after finding out that mixins somehow break it, i've ported it to events
![imagen](https://user-images.githubusercontent.com/68313143/141031241-6c68a269-b79d-4f66-b6a0-606d3b07f5d1.png)
so the solution is just to update :D
no one replied back about the sculk behavior after that update so i'll assume that it fixed it :0 but if you happen to have the same issue just let me know ^^

**Comment by ItsBlackGear** [comment]
i'll keep the issue open until i'm aware that it has been fixed 👀

**Comment by SHXRKIEgg** [comment]
Cool, I probs will update the packs in a week and let you know

**Comment by Symulation12** [comment]
I ran into this issue on my server today using the 7.1.3 version. The error message reads the same, so I figure it's a similar issue. I was able to replicate it by spawning two shulkers and getting them to attack each other until one attempted to teleport away. In case it's relevant, the world was generated using the 7.1 version and I ran into this issue before updating as well. After updating the mod in both server and client to 7.1.3 I was still able to replicate the issue.


Error message from the server: https://pastebin.com/MAyBhV0m

**Comment by ItsBlackGear** [comment]
okay that means that the issue persists, i think that i'll actually have to tweak that again

**Comment by MoonMoonShark** [comment]
am having the same issue on my server, if you need a world to use to test for troubleshooting purposes. i volunteer as tribute!

**Comment by SHXRKIEgg** [comment]
I can 100% confirm now its the Caves and Cliffs/Cave Biome API Mod. did a server with those 2 mods and after a couple of Shulkers hitting each other it crashed.
Here is a crash with just the 2 mods installed - https://pastebin.com/BhDMfAnv

**Comment by SharkieTV** [comment]
Any update on this?

**Comment by ItsBlackGear** [comment]
yup, it is confirmed, i've done some tests in a server and i finally got it working

**Comment by ItsBlackGear** [comment]
i'll release a new fix today, lemme know if that does work for you guys

**Comment by Symulation12** [comment]
Sounds good, I'll give it a shot as soon as it's available

**Comment by ItsBlackGear** [comment]
good, i'm literally uploading it rn

**Comment by ItsBlackGear** [comment]
it's out :D

**Comment by SHXRKIEgg** [comment]
Race to see who gets the crash first ;)

**Comment by ItsBlackGear** [comment]
i already tested in a server and got nothing xD

**Comment by SHXRKIEgg** [comment]
So far no crashing after multiple shulkers getting hit

**Comment by ItsBlackGear** [comment]
:D

**Comment by ItsBlackGear** [comment]
anything yet?

**Comment by Symulation12** [comment]
Not yet, been testing it by having tons of shulkers attack each other and haven't gotten anything yet

**Comment by ItsBlackGear** [comment]
good c: that means that the issue is finally solved (also when i was testing i saw them duplicating so i'm sure that it works c:)

**Comment by MoonMoonShark** [comment]
WOO! time for a shulker battle in the colosseum! \o/

**Comment by ItsBlackGear** [comment]
yass, i'll close this issue in that case c:
