### ISSUE TITLE
no copper ores of any kind drop from any kind of copper ores

### ISSUE THREAD

**Issue by kuba26038** [ItsBlackGear/CavesAndCliffsBackport#7]
i'm not sure why, but when i mine a copper ore of any kind nothing drops. i tested this with other mods such as create or tconstruct, and for some reason the bug would still persist. when i disabled the backport, all ores would drop their respective ores normally.

**Comment by ItsBlackGear** [comment]
That's weird.. tried disabling the raw copper ore drops from the config?

**Comment by kuba26038** [comment]
i instead deleted the text inside the raw_ores.json file via an datapack, due to which all ores started dropping normally. the issue is gone for me, but i'm still not sure if it's working for others...

**Comment by ItsBlackGear** [comment]
It has been working fine for others, no one has complained about them in
the discord server or cf comments
