### ISSUE TITLE
Mining Amethyst blocks returns the block, no shards

### ISSUE THREAD

**Issue by jacefri** [ItsBlackGear/CavesAndCliffsBackport#8]
Mining an Amethyst block should drop 2-4 Amethyst shards, but instead it just drops an Amethyst block.
Edit: Sorry my bad!

**Comment by StrangerSon71** [comment]
No, this is vanilla behavior. See the Minecraft Wiki.

**Comment by ItsBlackGear** [comment]
You get shard from mining the buds, mining the blocks shall give you the
block, it's vanilla behavior
