### ISSUE TITLE
[Request/Compat] Ability to disable Deepslate Ores

### ISSUE THREAD

**Issue by starryfae** [ItsBlackGear/CavesAndCliffsBackport#9]
This is super edge-case, but I am using Terraforged with Quark and Emendatus Enigmatica, even with KubeJS startup scripts (event.worldgenremove), your deeplate iron/gold/redstone spawns in Quark deepslate strata, (compat class) whch causes overlap with mods like AlltheOres or Emendatus Enigmatica.

I've tried several ways of preventing them from spawning but nothing works :/

I absolutely love how polished and well made your backport is, I love all the features, this is just a tiny bit of compat polish that would make your mod perfect to me.

Thank you, let me know if you need any more info.

**Comment by Pockett-Dev** [comment]
Agreed, I am heavily needing this implementation as well.

**Comment by ItsBlackGear** [comment]
Alright guys c: i'll see what can i do

**Comment by Pockett-Dev** [comment]
Thank you! Very much appreciated! :)

**Comment by starryfae** [comment]
Thank you! <3

**Comment by Pockett-Dev** [comment]
Sorry for the ping, but any updates on this? 😮

**Comment by ItsBlackGear** [comment]
fixed and pending for update c:
